[tox]
envlist = py310,py311,py312,py313,py314,pypy3
minversion = 4.0

[testenv]
usedevelop = true
extras =
  test
commands =
  python -W once -m testtools.run tests.test_suite {posargs}

[testenv:ruff]
description =
  Run style checks and reformat code.
deps =
  ruff
commands =
  ruff check --fix --unsafe-fixes --exit-non-zero-on-fix .
  ruff format .
