[tox]
envlist = py310,py311,py312,py313,py314,pypy3
minversion = 4.0

[testenv]
usedevelop = true
extras =
  test
commands = python -m testtools.run testresources.tests.test_suite

[testenv:ruff]
description =
  Run style checks and reformat code.
deps =
  ruff
commands =
  ruff format .
  ruff check --fix --unsafe-fixes --exit-non-zero-on-fix .
